name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: xcodebuild -project 'semaphor-test.xcodeproj' -scheme 'semaphor-test' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2' clean test
